FROM golang:1.13.6-alpine3.11 as builder
RUN apk --no-cache add git gcc make protobuf
RUN go get github.com/gogo/protobuf/protoc-gen-gofast

WORKDIR /app

ADD go.mod .
ADD go.sum .
ADD ./vendor ./vendor

ADD . .

RUN protoc -I. --gofast_out=plugins=grpc:. proto/tfc-transfer-validator.proto
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -mod vendor -o tfc-transfer-validator -a -installsuffix cgo ./main/main.go

FROM alpine:3.11.3
ENV app=tfc-transfer-validator

WORKDIR /app
COPY --from=builder /app/$app ./$app

CMD ./$app