// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tfc-transfer-validator.proto

package tfc_transfer_validator

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transfer_TransferType int32

const (
	Transfer_CARD Transfer_TransferType = 0
	Transfer_WIRE Transfer_TransferType = 1
)

var Transfer_TransferType_name = map[int32]string{
	0: "CARD",
	1: "WIRE",
}

var Transfer_TransferType_value = map[string]int32{
	"CARD": 0,
	"WIRE": 1,
}

func (x Transfer_TransferType) String() string {
	return proto.EnumName(Transfer_TransferType_name, int32(x))
}

func (Transfer_TransferType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb0390c139a8730c, []int{0, 0}
}

type Transfer struct {
	Origin               string                `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string                `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Amount               int32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 Transfer_TransferType `protobuf:"varint,4,opt,name=type,proto3,enum=tfc.transfer.validator.Transfer_TransferType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb0390c139a8730c, []int{0}
}

func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Transfer) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Transfer) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transfer) GetType() Transfer_TransferType {
	if m != nil {
		return m.Type
	}
	return Transfer_CARD
}

type TransferValidation struct {
	Transfer             *Transfer `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Validated            bool      `protobuf:"varint,2,opt,name=validated,proto3" json:"validated,omitempty"`
	Reason               string    `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TransferValidation) Reset()         { *m = TransferValidation{} }
func (m *TransferValidation) String() string { return proto.CompactTextString(m) }
func (*TransferValidation) ProtoMessage()    {}
func (*TransferValidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb0390c139a8730c, []int{1}
}

func (m *TransferValidation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferValidation.Unmarshal(m, b)
}
func (m *TransferValidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferValidation.Marshal(b, m, deterministic)
}
func (m *TransferValidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferValidation.Merge(m, src)
}
func (m *TransferValidation) XXX_Size() int {
	return xxx_messageInfo_TransferValidation.Size(m)
}
func (m *TransferValidation) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferValidation.DiscardUnknown(m)
}

var xxx_messageInfo_TransferValidation proto.InternalMessageInfo

func (m *TransferValidation) GetTransfer() *Transfer {
	if m != nil {
		return m.Transfer
	}
	return nil
}

func (m *TransferValidation) GetValidated() bool {
	if m != nil {
		return m.Validated
	}
	return false
}

func (m *TransferValidation) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterEnum("tfc.transfer.validator.Transfer_TransferType", Transfer_TransferType_name, Transfer_TransferType_value)
	proto.RegisterType((*Transfer)(nil), "tfc.transfer.validator.Transfer")
	proto.RegisterType((*TransferValidation)(nil), "tfc.transfer.validator.TransferValidation")
}

func init() { proto.RegisterFile("tfc-transfer-validator.proto", fileDescriptor_cb0390c139a8730c) }

var fileDescriptor_cb0390c139a8730c = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xf4, 0x30,
	0x14, 0x85, 0x27, 0xff, 0xf4, 0x1f, 0xda, 0x3b, 0x22, 0x43, 0x16, 0x43, 0x91, 0x59, 0x84, 0xac,
	0x8a, 0xd0, 0x2c, 0xea, 0xd6, 0xcd, 0xa0, 0x2e, 0xdc, 0x49, 0x1c, 0x75, 0x1d, 0xdb, 0x54, 0x02,
	0x9a, 0xd4, 0x34, 0x0e, 0xf4, 0x0d, 0x7c, 0x2f, 0x5f, 0x4c, 0x1a, 0xd3, 0xce, 0x20, 0x42, 0x77,
	0xf7, 0x9e, 0x73, 0x4f, 0xfb, 0x1d, 0x02, 0x1b, 0x57, 0x97, 0xb9, 0xb3, 0x42, 0xb7, 0xb5, 0xb4,
	0xf9, 0x5e, 0xbc, 0xaa, 0x4a, 0x38, 0x63, 0x59, 0x63, 0x8d, 0x33, 0x78, 0xed, 0xea, 0x92, 0x0d,
	0x2e, 0x1b, 0x5d, 0xfa, 0x85, 0x20, 0xde, 0x05, 0x19, 0xaf, 0x61, 0x61, 0xac, 0x7a, 0x51, 0x3a,
	0x45, 0x04, 0x65, 0x09, 0x0f, 0x1b, 0x26, 0xb0, 0xac, 0x64, 0xeb, 0x94, 0x16, 0x4e, 0x19, 0x9d,
	0xfe, 0xf3, 0xe6, 0xb1, 0xd4, 0x27, 0xc5, 0x9b, 0xf9, 0xd0, 0x2e, 0x9d, 0x13, 0x94, 0xfd, 0xe7,
	0x61, 0xc3, 0x5b, 0x88, 0x5c, 0xd7, 0xc8, 0x34, 0x22, 0x28, 0x3b, 0x2d, 0x72, 0xf6, 0x37, 0x05,
	0x1b, 0x08, 0xc6, 0x61, 0xd7, 0x35, 0x92, 0xfb, 0x28, 0xa5, 0x70, 0x72, 0xac, 0xe2, 0x18, 0xa2,
	0xab, 0x2d, 0xbf, 0x5e, 0xcd, 0xfa, 0xe9, 0xe9, 0x96, 0xdf, 0xac, 0x10, 0xfd, 0x44, 0x80, 0x87,
	0xa3, 0xc7, 0x9f, 0xaf, 0xf6, 0x54, 0x97, 0x10, 0x0f, 0x3f, 0xf3, 0x8d, 0x96, 0x05, 0x99, 0x22,
	0xe0, 0x63, 0x02, 0x6f, 0x20, 0x09, 0xbe, 0xac, 0x7c, 0xe7, 0x98, 0x1f, 0x84, 0xbe, 0xb1, 0x95,
	0xa2, 0x35, 0xda, 0x37, 0x4e, 0x78, 0xd8, 0x8a, 0x77, 0x48, 0x7f, 0x91, 0x18, 0x7b, 0x2f, 0xed,
	0x5e, 0x95, 0x12, 0x3f, 0xc0, 0xfc, 0x4e, 0x74, 0x78, 0x12, 0xe2, 0xec, 0x7c, 0xea, 0xe2, 0x50,
	0x92, 0xce, 0x9e, 0x17, 0xfe, 0x89, 0x2f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x18, 0x8c, 0x81,
	0xa1, 0x02, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransferValidatorServiceClient is the client API for TransferValidatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransferValidatorServiceClient interface {
	Pay(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*TransferValidation, error)
}

type transferValidatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransferValidatorServiceClient(cc *grpc.ClientConn) TransferValidatorServiceClient {
	return &transferValidatorServiceClient{cc}
}

func (c *transferValidatorServiceClient) Pay(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*TransferValidation, error) {
	out := new(TransferValidation)
	err := c.cc.Invoke(ctx, "/tfc.transfer.validator.TransferValidatorService/Pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferValidatorServiceServer is the server API for TransferValidatorService service.
type TransferValidatorServiceServer interface {
	Pay(context.Context, *Transfer) (*TransferValidation, error)
}

// UnimplementedTransferValidatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransferValidatorServiceServer struct {
}

func (*UnimplementedTransferValidatorServiceServer) Pay(ctx context.Context, req *Transfer) (*TransferValidation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pay not implemented")
}

func RegisterTransferValidatorServiceServer(s *grpc.Server, srv TransferValidatorServiceServer) {
	s.RegisterService(&_TransferValidatorService_serviceDesc, srv)
}

func _TransferValidatorService_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferValidatorServiceServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tfc.transfer.validator.TransferValidatorService/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferValidatorServiceServer).Pay(ctx, req.(*Transfer))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransferValidatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tfc.transfer.validator.TransferValidatorService",
	HandlerType: (*TransferValidatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pay",
			Handler:    _TransferValidatorService_Pay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tfc-transfer-validator.proto",
}
