// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transfer-service.proto

package transferservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transfer_TransferType int32

const (
	Transfer_CARD Transfer_TransferType = 0
	Transfer_WIRE Transfer_TransferType = 1
)

var Transfer_TransferType_name = map[int32]string{
	0: "CARD",
	1: "WIRE",
}

var Transfer_TransferType_value = map[string]int32{
	"CARD": 0,
	"WIRE": 1,
}

func (x Transfer_TransferType) String() string {
	return proto.EnumName(Transfer_TransferType_name, int32(x))
}

func (Transfer_TransferType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b3356ba5b8659c61, []int{0, 0}
}

type Transfer struct {
	Origin               int64                 `protobuf:"varint,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          int64                 `protobuf:"varint,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Amount               int32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 Transfer_TransferType `protobuf:"varint,4,opt,name=type,proto3,enum=transferservice.Transfer_TransferType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3356ba5b8659c61, []int{0}
}

func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetOrigin() int64 {
	if m != nil {
		return m.Origin
	}
	return 0
}

func (m *Transfer) GetDestination() int64 {
	if m != nil {
		return m.Destination
	}
	return 0
}

func (m *Transfer) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transfer) GetType() Transfer_TransferType {
	if m != nil {
		return m.Type
	}
	return Transfer_CARD
}

type TransferValidation struct {
	Transfer             *Transfer `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Validated            bool      `protobuf:"varint,2,opt,name=validated,proto3" json:"validated,omitempty"`
	Reason               string    `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TransferValidation) Reset()         { *m = TransferValidation{} }
func (m *TransferValidation) String() string { return proto.CompactTextString(m) }
func (*TransferValidation) ProtoMessage()    {}
func (*TransferValidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3356ba5b8659c61, []int{1}
}

func (m *TransferValidation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferValidation.Unmarshal(m, b)
}
func (m *TransferValidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferValidation.Marshal(b, m, deterministic)
}
func (m *TransferValidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferValidation.Merge(m, src)
}
func (m *TransferValidation) XXX_Size() int {
	return xxx_messageInfo_TransferValidation.Size(m)
}
func (m *TransferValidation) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferValidation.DiscardUnknown(m)
}

var xxx_messageInfo_TransferValidation proto.InternalMessageInfo

func (m *TransferValidation) GetTransfer() *Transfer {
	if m != nil {
		return m.Transfer
	}
	return nil
}

func (m *TransferValidation) GetValidated() bool {
	if m != nil {
		return m.Validated
	}
	return false
}

func (m *TransferValidation) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterEnum("transferservice.Transfer_TransferType", Transfer_TransferType_name, Transfer_TransferType_value)
	proto.RegisterType((*Transfer)(nil), "transferservice.Transfer")
	proto.RegisterType((*TransferValidation)(nil), "transferservice.TransferValidation")
}

func init() { proto.RegisterFile("transfer-service.proto", fileDescriptor_b3356ba5b8659c61) }

var fileDescriptor_b3356ba5b8659c61 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xbb, 0x26, 0x96, 0x74, 0x2a, 0x5a, 0xe7, 0x50, 0xa2, 0x78, 0x08, 0x2b, 0x48, 0x2e,
	0xe6, 0x10, 0xf1, 0xe2, 0x4d, 0x54, 0xc4, 0xeb, 0x52, 0xf4, 0xe2, 0x65, 0x35, 0xa3, 0x2c, 0xe8,
	0x6e, 0xd8, 0xac, 0x85, 0x1c, 0xfd, 0x5f, 0xfe, 0x38, 0xc9, 0x76, 0xd3, 0x96, 0x42, 0x6e, 0xf3,
	0xbe, 0x99, 0xd9, 0x37, 0x8f, 0x85, 0xb9, 0xb3, 0x52, 0x37, 0x1f, 0x64, 0x2f, 0x1b, 0xb2, 0x4b,
	0xf5, 0x4e, 0x45, 0x6d, 0x8d, 0x33, 0x78, 0xd4, 0xf3, 0x80, 0xf9, 0x1f, 0x83, 0x64, 0x11, 0x18,
	0xce, 0x61, 0x6c, 0xac, 0xfa, 0x54, 0x3a, 0x65, 0x19, 0xcb, 0x23, 0x11, 0x14, 0x66, 0x30, 0xad,
	0xa8, 0x71, 0x4a, 0x4b, 0xa7, 0x8c, 0x4e, 0xf7, 0x7c, 0x73, 0x1b, 0x75, 0x9b, 0xf2, 0xdb, 0xfc,
	0x68, 0x97, 0x46, 0x19, 0xcb, 0xf7, 0x45, 0x50, 0x78, 0x03, 0xb1, 0x6b, 0x6b, 0x4a, 0xe3, 0x8c,
	0xe5, 0x87, 0xe5, 0x45, 0xb1, 0x63, 0x5f, 0xf4, 0xd6, 0xeb, 0x62, 0xd1, 0xd6, 0x24, 0xfc, 0x0e,
	0xe7, 0x70, 0xb0, 0x4d, 0x31, 0x81, 0xf8, 0xee, 0x56, 0xdc, 0xcf, 0x46, 0x5d, 0xf5, 0xf2, 0x24,
	0x1e, 0x66, 0x8c, 0xff, 0x32, 0xc0, 0x7e, 0xe8, 0x59, 0x7e, 0xa9, 0x6a, 0x75, 0xce, 0x35, 0x24,
	0xbd, 0x93, 0x8f, 0x32, 0x2d, 0x4f, 0x06, 0xad, 0xc5, 0x7a, 0x14, 0xcf, 0x60, 0xb2, 0x5c, 0x3d,
	0x42, 0x95, 0x4f, 0x99, 0x88, 0x0d, 0xe8, 0x32, 0x5a, 0x92, 0x8d, 0xd1, 0x3e, 0xe3, 0x44, 0x04,
	0x55, 0xbe, 0xc2, 0xf1, 0xce, 0x09, 0xc6, 0xe2, 0x23, 0x44, 0xb5, 0x6c, 0x71, 0xd8, 0xf6, 0xf4,
	0x7c, 0xb0, 0xb5, 0x09, 0xc2, 0x47, 0x6f, 0x63, 0xff, 0x71, 0x57, 0xff, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x46, 0xf8, 0xc4, 0xf9, 0xd2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransferValidatorClient is the client API for TransferValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransferValidatorClient interface {
	Pay(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*TransferValidation, error)
}

type transferValidatorClient struct {
	cc *grpc.ClientConn
}

func NewTransferValidatorClient(cc *grpc.ClientConn) TransferValidatorClient {
	return &transferValidatorClient{cc}
}

func (c *transferValidatorClient) Pay(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*TransferValidation, error) {
	out := new(TransferValidation)
	err := c.cc.Invoke(ctx, "/transferservice.TransferValidator/pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferValidatorServer is the server API for TransferValidator service.
type TransferValidatorServer interface {
	Pay(context.Context, *Transfer) (*TransferValidation, error)
}

// UnimplementedTransferValidatorServer can be embedded to have forward compatible implementations.
type UnimplementedTransferValidatorServer struct {
}

func (*UnimplementedTransferValidatorServer) Pay(ctx context.Context, req *Transfer) (*TransferValidation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pay not implemented")
}

func RegisterTransferValidatorServer(s *grpc.Server, srv TransferValidatorServer) {
	s.RegisterService(&_TransferValidator_serviceDesc, srv)
}

func _TransferValidator_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferValidatorServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transferservice.TransferValidator/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferValidatorServer).Pay(ctx, req.(*Transfer))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransferValidator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transferservice.TransferValidator",
	HandlerType: (*TransferValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "pay",
			Handler:    _TransferValidator_Pay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transfer-service.proto",
}
